repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3  # Use the ref you want to point at
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100000']
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
        args: ['--autofix', '--no-sort-keys']
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: sort-simple-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: no-commit-to-branch
        args: [--branch, master]
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    # -   id: ...
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      args: ["--line-length=100"]
      language_version: python3.8
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
      args: ["--max-line-length=100","--ignore=E501,W503,E203,E402"]
      language_version: python3.8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3.8
